src/urls.py
"""
This module bind views with url.
"""
from app import app, db
from flask.ext.restless import APIManager
from user.views import user_module
from endpoints.api import (
    user_api, blog_api,
    feature_api, document_api
)

# url registration.
app.register_blueprint(user_module) # registering Blueprint

# registering API
app.register_blueprint(user_api)
app.register_blueprint(blog_api)
app.register_blueprint(feature_api)
app.register_blueprint(document_api)

urls.py
"""
This module bind views with url.
"""
from app import app
import views


# urls binding with views.
app.add_url_rule('/', view_func=views.index)
app.add_url_rule('/hello/<name>/', view_func=views.test)
app.add_url_rule('/showServices', view_func=views.showServices)
app.add_url_rule('/about', view_func=views.about)
app.add_url_rule('/logout', view_func=views.logout)
app.add_url_rule('/showPortfolio', view_func=views.showPortfolio)
app.add_url_rule('/signUp', view_func=views.UserSignUp.as_view('signUp'))
app.add_url_rule('/signIn', view_func=views.UserSignIn.as_view('signIn'))
#app.add_url_rule('/signIn', view_func=views.signIn, methods=['GET', 'POST'])

src/blog/models.py
"""
Blog modules.
"""
from app import db
from utils.base import BaseModel
from sqlalchemy.orm import relationship, backref


class Blog(BaseModel):
    """
    should create blog tables.
    """
    __tablename__ = 'blog'

    id = db.Column(db.Integer, primary_key=True)
    account_number = db.Column(db.String(256))
    url = db.Column(db.String(128))

    def __init__(self, account_number, url):
        self.account_number = account_number
        self.url = url

    def __repr__(self):
        return '<blog_url {})>'.format(self.blog_url)


class UserBlog(BaseModel):
    """
    should create user blog table.
    """
    __tablename__ = 'user_blog'

    id = db.Column(db.Integer, db.Sequence('user_blog_seq'), primary_key=True)
    blog_id = db.Column(db.Integer, db.ForeignKey('blog.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __init__(self, blog_id, user_id):
        self.blog_id = blog_id
        self.user_id = user_id

src/document/models.py
"""
document modules.
"""
from app import db
from utils.base import BaseModel


class Document(BaseModel):
    """
    should create document tables.
    """
    __tablename__ = 'document'

    id = db.Column(db.Integer, primary_key=True)
    path = db.Column(db.String(128))
    size = db.Column(db.String(128))

    def __init__(self, path, size):
        self.path = path
        self.size = size

src/feature/models.py
"""
Feature modules.
"""
from app import db
from utils.base import BaseModel
from sqlalchemy.orm import relationship, backref


class Feature(BaseModel):
    """
    should create feature tables.
    """
    __tablename__ = 'feature'

    id = db.Column(db.Integer, primary_key=True)
    slug = db.Column(db.String(128))
    name = db.Column(db.String(128))
    blog_id = db.Column(db.Integer, db.ForeignKey('blog.id'))
    #blog = relationship('Blog', backref=backref('feature', lazy='dynamic'))


    def __init__(self, slug, name, blog_id):
        self.slug = slug
        self.name = name
        self.blog_id = blog_id

    def __repr__(self):
        return '<Feature {})>'.format(self.name)

src/user/models.py
from app import db
from utils.base import BaseModel
from werkzeug import generate_password_hash, check_password_hash


class User(BaseModel):
    """
    should create user table.
    """
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(128))
    first_name = db.Column(db.String(128))
    last_name = db.Column(db.String(128))
    email = db.Column(db.String(128))
    password = db.Column(db.String(128))
    contact = db.Column(db.String(128))

    def __init__(self,
                 username, password, firstname, lastname, email):
        self.username = username
        self.set_password(password)
        self.first_name = firstname
        self.last_name = lastname
        self.email = email

    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    def get_id(self):
        return unicode(self.id)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<username {}>'.format(self.username)

src/user/views.py
"""
Views module .
"""
from app import app, db, mail
from flask.views import MethodView
from flask import (Flask, render_template, request,
                   json, flash, redirect, url_for, Blueprint)
from flask.ext.login import login_user, logout_user, current_user
from werkzeug import generate_password_hash, check_password_hash
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.login import LoginManager
from utils.utility import login_required
from models import User
from flask_mail import Mail, Message
from flask.ext.api import status
from form import SigninForm, SignupForm
from flask.ext.api.renderers import JSONRenderer
from flask.ext.api.decorators import set_renderers


user_module = Blueprint('user', __name__)

# routing configuration.
login_manager = LoginManager()
login_manager.init_app(app)

@user_module.route('/')
def index():
    """
    Displays the index page accessible at '/'
    """
    return render_template('index.html')

@user_module.route('/hello/<name>/')
def test(name):
    """
    Displays the page greats who ever comes to visit it.
    """
    return render_template('hello.html', name=name)

@user_module.route('/showServices')
@login_required
def showServices():
    """
    Display services .
    """
    return render_template('services.html')

@user_module.route('/about')
@login_required
def about():
     """
     Display portfolio.
     """
     return render_template('about.html')

@user_module.route('/showPortfolio')
@login_required
def showPortfolio():
     """
     Display portfolio.
     """
     return render_template('portfolio.html')

@app.errorhandler(404)
def page_not_found(error):
    """
    Display error page if url not matched.
    """
    return render_template('error.html')

@login_manager.user_loader
def user_loader(user_id):
    user = User.query.filter_by(id=user_id)
    if user.count() == 1:
        return user.one()
    return None

@user_module.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('user.index'))


class UserSignUp(MethodView):
    """
    user registration views.
    """
    def get(self):
        return render_template('signup.html')

    def post(self):
        form = SignupForm(request.form)
        print("form validate", form.validate())
        print("form errors", form.errors)
        if form.validate()==False:
            print("form errors", form.errors)
            return render_template('signup.html', form=form)
        else:
            #import pdb;pdb.set_trace();
            user = User(
                username=form.username.data,
                password=form.password.data,
                firstname=form.firstname.data,
                lastname=form.lastname.data,
                email=form.email.data
            )
            db.session.add(user)
            db.session.commit()
            msg = Message(
                'Hello'+' '+form.firstname.data+' '+form.lastname.data,
                sender='deepak.dubey@vertisinfotech.com',
                recipients=[form.email.data])
            msg.body = 'Thanks for signup , we will get in touch with you soon!!!'
            mail.send(msg)
            user = User.query.all()
            print("users are :: ", user)
            print("@@@@@@@@@@@ redirected to showSignIn part")
            return redirect(url_for('user.index'))


class UserSignIn(MethodView):
    """
    views to make user login.
    """
    def get(self):
        return render_template('signin.html')

    def post(self):
        form = SigninForm(request.form)
        print("value of form.validate:::::", form.validate())
        if form.validate()==False:
            return render_template('signin.html')
        else:
            user = User.query.filter_by(username=form.username.data)
            login_user(user.one())
            flash('Welcome back {0}'.format(form.username.data))
            print("@@@@@@@@@@@@Login successfully!!!!!")
            return redirect(url_for('user.index'))

# regestering classbased views with blue_print user_module
user_module.add_url_rule('/signUp', view_func=UserSignUp.as_view('signUp'))
user_module.add_url_rule('/signIn', view_func=UserSignIn.as_view('signIn'))

src/templates/about.html
{% extends "master.html" %}

{% block background_image %}
<body background="static/img/5.jpg"/>
  {% endblock %}

  {% block nav_ul %}
  <li role="presentation"><a href="{{ url_for('user.index') }}">Home</a></li>
  <li role="presentation" class="active"><a href="/about">About</a></li>
  <li role="presentation"><a href="{{ url_for('user.showServices') }}">Service</a></li>
  <li role="presentation"><a href="{{ url_for('user.showPortfolio') }}">Portfolio</a></li>
  {% endblock %}

  {% block ss %}
  <li role="presentation"><a href="{{ url_for('user.signIn') }}">SignIn</a></li>
  <li role="presentation"><a href="{{ url_for('user.signUp') }}">SignUp</a></li>
  {% endblock %}

  {% block portfolio %}

  <table class="table table-hover">
    <thead>
      <tr>
	<th>First Name</th>
	<th>Last Name</th>
	<th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for current_user in users %}
      <tr>
	<td>{{ current_user.first_name }}</td>
	<td>{{ current_user.last_name }}</td>
	<td>{{ current_user.email }}</td>
      </tr>
      {% endfor %}>
    </tbody>
  </table>

  {% endblock %}

  {% block jumbotron %}
  {% endblock %}

src/templates/activate.html
<p>Welcome! Thanks for signing up. Please follow this link to activate your account:</p>
<p><a href="{{ confirm_url }}">{{ confirm_url }}</a></p>
<br>
<p>Cheers!</p>

src/templates/error.html
<html lang="en">
  <head>
    <title>Flask</title>


    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <link href="http://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <link type="text/css" rel="stylesheet"
          href="{{url_for('static',
                filename='signup.css')}}" />
  </head>
  <body>
    <div class="container">
      <div class="header">
        <nav>
          <ul class="nav nav-pills pull-right">
            <li role="presentation" ><a href="{{ url_for('user.index') }}">Home</a></li>
            <li role="presentation"><a href="#">About</a></li>
            <li role="presentation"><a href="#">Service</a></li>
            <li role="presentation"><a href="#">Portfolio</a></li>
            <li role="presentation"><a href="showSignIn">Sign In</a></li>
            <li role="presentation" class="active"><a href="#">Sign Up</a></li>
          </ul>
        </nav>
        <h3 class="text-muted">@Flask App</h3>
      </div>
      <div class="jumbotron">
        <img src="static/img/404-error.jpg">
      </div>
      <footer class="footer">
        <p>&copy; Company 2016</p>
      </footer>
    </div>
  </body>
</html>

src/templates/hello.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8" />
    <title>Hello</title>
    <link type="text/css" rel="stylesheet"
          href="{{ url_for('static/css/',
                filename='angular-material.css')}}" />
  </head>
  <body>
    <a href="{{ url_for('user.index') }}"><button>Back</button></a>
    <center><h2>Hello {{name}}<h2></center>
  </body>
</html>

src/templates/index.html
{% extends "master.html" %}
{% block title %}Home{% endblock %}
{% block portfolio %}
{% endblock %}
{% block jumbotron %}
{% endblock %}

src/templates/master.html
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %} - Hello Flask!</title>
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
    <link href="https://getbootstrap.com/examples/jumbotron-narrow/jumbotron-narrow.css" rel="stylesheet">
    <script src="/static/js/signup.js" type="text/javascript"></script>
    <script>
      $(document).ready(function () {
      $('.dropdown-toggle').dropdown();
      });
    </script>
  </head>
  {% block background_image %}
  <body background="static/img/9.jpg">
    {% endblock %}
    <div class="container">
      <div class="header">
	<nav>
	  <ul class="nav nav-pills pull-right">
	    {% block nav_ul %}
	    <li role="presentation" class="active"><a href="#">Home</a></li>
	    <li role="presentation"><a href="/about">About</a></li>
	    <li role="presentation"><a href="/showServices">Service</a></li>
	    <li role="presentation"><a href="/showPortfolio">Portfolio</a></li>
	    {% endblock %}
	    {% if current_user.is_authenticated %}
	    <li class="dropdown">
	      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="true">
		<strong>{{ current_user.username }}</strong>
		<span class="caret"></span>
	      </a>
	      <ul class="dropdown-menu">
		<li><a href="{{ url_for('user.about') }}">Profile</a></li>
		<li><a href="#">Change password</a></li>
		<li><a href="#">Your Blog</a></li>
		<li><a href="{{ url_for('user.showPortfolio') }}">Meet Your Team</a></li>
		<li><a href="#">Invite Freinds</a></li>
		<li><a href="/logout">Logout</a></li>
	      </ul>
	    </li>
	    {% else %}
	    {% block ss %}
	    <li role="presentation"><a href="/signIn">SignIn</a></li>
	    <li role="presentation"><a href="/signUp">SignUp</a></li>
	    {% endblock %}
	    {% endif %}
	  </ul>
	</nav>
	<h3 class="text-muted">@Flask App</h3>
      </div>
      {% block portfolio %}
      {% if current_user.is_authenticated %}
      <div class="jumbotron">
	<h3><strong> Python Team</strong> !!!</h3>
      </div>

      <div class="row">
	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/arun.jpg" alt="Arun Mittal">
	    <h5>Arun Mittal<br>
	      <small>Python Lead Developer</small>
	    </h5>
	  </a>
	</div>

	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/user.jpg" alt="Pranav Gore">
	    <h5>Pranav Gore<br>
	      <small>Python Developer</small>
	    </h5>
	  </a>
	</div>

	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/sagar.jpg" alt="Sagar Talekar">
	    <h5>Sagar Talekar<br>
	      <small>Python Developer</small>
	    </h5>

	  </a>
	</div>
      </div>

      <div class="row">
	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/user1.jpg" alt="Siddartrh Sonavane">
	    <h5>Siddarth Sonavane<br>
	      <small>Python Developer</small>
	    </h5>
	  </a>
	</div>

	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/user.jpg" alt="Deepak Kumar Dubey">
	    <h5>Deepak Kumar Dubey<br>
	      <small>Python Developer</small>
	    </h5>
	  </a>
	</div>

	<div class="col-xs-6 col-md-4">
	  <a href="#" class="thumbnail">
	    <img src="static/img/user.jpg" alt="Deepak Kumar Dubey">
	    <h5>Swapnil Pandit<br>
	      <small>Python Developer</small>
	    </h5>
	  </a>
	</div>
      </div>
      {% else %}
      {% block body %}{% endblock %}
      {% endif %}
      {% endblock %}

      {% if current_user.is_authenticated %}
      {% block jumbotron %}
      <div class="jumbotron">
	<h3>Hi, You are Logged in with User Name <strong>{{ current_user.username }}</strong> !!!</h3>
      </div>
      {% endblock %}
      {% else %}
      {% block body1 %}{% endblock %}
      {% endif %}
    </div>
  </body>
</html>

src/templates/not_confirmed.html
{% extends "_base.html" %}

{% block content %}

<h1>Welcome!</h1>
<br>
<p>You have not confirmed your account. Please check your inbox (and your spam folder) - you should have received an email with a confirmation link.</p>
<p>Didn't get the email? <a href="{{ url_for('user.resend_confirmation') }}">Resend</a>.</p>

{% endblock %}

src/templates/portfolio.html
{% extends "master.html" %}
{% block title %}Home{% endblock %}

{% block background_image %}
<body background="static/img/5.jpg">
  {% endblock %}

  {% block nav_ul %}
  <li role="presentation" ><a href="{{ url_for('user.index') }}">Home</a></li>
  <li role="presentation"><a href="{{ url_for('user.about') }}">About</a></li>
  <li role="presentation"><a href="{{ url_for('user.showServices') }}">Service</a></li>
  <li role="presentation" class="active"><a href="{{ url_for('user.showPortfolio') }}">Portfolio</a></li>
  {% endblock %}

  {% block ss %}
  <li role="presentation"><a href="{{ url_for('user.signIn') }}">SignIn</a></li>
  <li role="presentation"><a href="{{ url_for('user.signUp') }}">SignUp</a></li>
  {% endblock %}

  {% block jumbotron %}
  {% endblock %}

src/templates/services.html
{% extends "master.html" %}
{% block title %}Home{% endblock %}

{% block background_image %}
<body background="static/img/5.jpg">
  {% endblock %}
  {% block nav_ul %}
  <li role="presentation" ><a href="{{ url_for('user.index') }}">Home</a></li>
  <li role="presentation"><a href="{{ url_for('user.about') }}">About</a></li>
  <li role="presentation" class="active"><a href="/showServices">Service</a></li>
  <li role="presentation"><a href="{{ url_for('user.showPortfolio') }}">Portfolio</a></li>
  {% endblock %}

  {% block ss %}
  <li role="presentation"><a href="{{ url_for('user.signIn') }}">SignIn</a></li>
  <li role="presentation"><a href="{{ url_for('user.signUp') }}">SignUp</a></li>
  {% endblock %}

  {% block portfolio %}
  {% endblock %}
  {% block jumbotron %}
  {% endblock %}

src/templates/signin.html
{% extends "master.html" %}

{% block nav_ul %}
<li role="presentation" ><a href="{{ url_for('user.index') }}">Home</a></li>
<li role="presentation"><a href="{{ url_for('user.about') }}">About</a></li>
<li role="presentation"><a href="{{ url_for('user.showServices') }}">Service</a></li>
<li role="presentation"><a href="{{ url_for('user.showPortfolio') }}">Portfolio</a></li>
<li role="presentation" class="active"><a href="signIn">SignIn</a></li>
<li role="presentation"><a href="{{ url_for('user.signUp') }}">SignUp</a></li>
{% endblock %}

{% block ss %}
{% endblock %}

{% block portfolio %}
<div class="jumbotron" style="opacity:0.75">
  <img src="static/img/signin.png">
  <form class="form-signin" action="{{ url_for('user.signIn') }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <label for="name" class="sr-only">User Name</label><br>
    <input type="name" name="username" id="username" class="form-control" placeholder="User Name" required autofocus><br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="password" class="form-control" placeholder="Password" required><br>
    <button id="btnSignIn" class="btn btn-lg btn-primary btn-block" type="submit">Login</button>
  </form>
</div>
<footer class="footer">
  <p>&copy; Company 2016</p>
</footer>
{% endblock %}
{% block jumbotron %}
{% endblock %}

src/templates/signup.html
{% extends "master.html" %}
{% block nav_ul %}
<li role="presentation" ><a href="{{ url_for('user.index') }}">Home</a></li>
<li role="presentation"><a href="{{ url_for('user.about') }}">About</a></li>
<li role="presentation"><a href="{{ url_for('user.showServices') }}">Service</a></li>
<li role="presentation"><a href="{{ url_for('user.showPortfolio') }}">Portfolio</a></li>
{% if current_user.is_authenticated %}
<li role="presentation" class="active"><a href="/logout">Logout</a></li>
{% else %}
<li role="presentation"><a href="{{ url_for('user.signIn') }}">SignIn</a></li>
<li role="presentation" class="active"><a href="/signUp">SignUp</a></li>
{% endif %}
{% endblock %}

{% block ss %}
{% endblock %}

{% block portfolio %}
<div class="jumbotron" style="opacity: 0.75">
  <img src="static/img/signup1.jpg">
  <form class="form-signin" action="{{ url_for('user.signUp') }}" method="POST">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <label for="inputName" class="sr-only">User Name</label><br>
    <input type="name" name="username" id="userName" class="form-control" placeholder="User Name" required autofocus>
    <label for="inputName" class="sr-only">First Name</label><br>
    <input type="name" name="firstname" id="firstName" class="form-control" placeholder="First Name" required autofocus>
    <label for="inputName" class="sr-only">Last Name</label><br>
    <input type="name" name="lastname" id="lastName" class="form-control" placeholder="Last Name" required autofocus>
    <label for="inputEmail" class="sr-only">Email address</label><br>
    <input type="email" name="email" id="email" class="form-control" placeholder="Email address" required autofocus><br>
    <label for="inputPassword" class="sr-only">Password</label>
    <input type="password" name="password" id="password" class="form-control" placeholder="Password" required><br>
    <button id="btnSignUp" class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
  </form>
</div>
<footer class="footer">
  <p>&copy; Company 2016</p>
</footer>
{% endblock %}
{% block jumbotron %}
{% endblock %}